# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SkyTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for SkyTest
  pod 'Alamofire'
  pod 'SDWebImage'
  pod 'ObjectMapper'
  
  target 'SkyTestTests' do
    inherit! :search_paths
    # Pods for testing
  end
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if ['Alamofire', 'SwiftMessages', 'SDWebImage', 'ObjectMapper', 'SwiftyJSON'].include? target.name
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '4.2'
        end
      end
    end
  end
  
end
